# Run at *build* time (cmake -P) to record which commit the binary was built from, for the run-log header.
# Rewrites the output only when the content changes, so an unchanged tree causes no rebuild.
#   -DSOURCE_DIR=<repo> -DOUTPUT=<file.cpp>

execute_process(COMMAND git -C "${SOURCE_DIR}" rev-parse --short=12 HEAD
                OUTPUT_VARIABLE commit OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  set(commit "unknown")
endif()
# Dirty = uncommitted changes to tracked files (untracked files don't count).
execute_process(COMMAND git -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
                OUTPUT_VARIABLE status ERROR_QUIET)
if(status STREQUAL "")
  set(dirty false)
else()
  set(dirty true)
endif()

string(CONCAT content "// Generated by cmake/git_info.cmake — do not edit.\n#include \"core/build_info.h\"\n\n"
            "namespace glint::build {\nconst char* const kGitCommit = \"${commit}\";\n"
            "const bool kGitDirty = ${dirty};\n}  // namespace glint::build\n")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old)
endif()
if(NOT "${old}" STREQUAL "${content}")
  file(WRITE "${OUTPUT}" "${content}")
endif()
